version: "3"

services:
  oms-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:9091
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/oms_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=oms_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped



volumes:
  postgres:
  pgadmin: